version: '3.8'

services:
  temporal:
    image: temporalio/server:latest
    environment:
      - TEMPORAL_BROADCAST_ADDRESS=0.0.0.0
    ports:
      - "7233:7233"  # gRPC for .NET client and CLI
      - "8080:8080"  # Web UI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge